### PR TITLE
Define a default provider if there is only one provider

### PR DESCRIPTION
**Pull request by messense**
So I don't have to input `0` and hit enter every time.

### CODE REVIEW

**Comment by luxiaba** [comment]
I think it's better for users to clearly know his operation.
And after choose provider, next operation is create server, it's about money maybe, so it's better not to automation operation before this.

**Comment by messense** [comment]
It's not automated, it just skips the `input 0` part, user still needs to hit enter.

**Comment by luxiaba** [comment]
I see, sounds make sense, let me try first.

**Review by laixintao — APPROVED** [review]
Very nice, I had the same idea.

**Pull request merged**
